configuracao/urls.py
from django.conf.urls import url
urlpatterns = [
    url(),
]

login/urls.py
from django.conf.urls import url
from login.views import Login, CadastrarUsuario
urlpatterns = [
    url(r'^$', Login.as_view(), name='login'),
    url(r'^usuarios/$',CadastrarUsuario.as_view(), name='usuarios')
]

people/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pessoa.urls')),
    path('login/', include('login.urls')),
    #path('conf/', include('configuracao.urls')),
]

pessoa/urls.py
from django.conf.urls import url
from pessoa.views import index, CadastroPessoaView, PeopleSearch, PeopleDetails
urlpatterns = [
   url(r'^$',index,name = 'index'),
   url(r'^cadastro_pessoa/$',CadastroPessoaView.as_view(), name='cadastro_pessoa'),
   url(r'^pessoa_search/$',PeopleSearch.as_view(),name='pessoa_search'),
   url(r'^details/(?P<pessoa_id>\d+)$',PeopleDetails.as_view(),name='details'),
]

configuracao/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.
class Usuario(models.Model):
    nome_user = models.CharField(max_length = 100)
    usuario = models.CharField(max_length = 50)
    senha = models.CharField(max_length = 50)
    perfil = models.CharField(max_length = 10)

    class Meta:
        db_table = 'users'

    def __str__(self):
        return self.nome_user

pessoa/models.py
from django.db import models

# Create your models here.

class  Pessoa(models.Model):
    nome = models.CharField(max_length=100)
    titulo= models.CharField(max_length=12)
    cpf = models.CharField(max_length=11)
    telefone = models.CharField(max_length=15)
    email = models.CharField(max_length=50)
    flag_delete = models.CharField(max_length=1)
    #Endereco
    rua = models.CharField(max_length=100)
    numero = models.CharField(max_length=10)
    bairro = models.CharField(max_length=50)
    cep = models.CharField(max_length=8)
    bloco = models.CharField(max_length=3)
    apartamento = models.CharField(max_length=4)
    complemento = models.CharField(max_length=20)
    def publish(self):
        self.save()

    def __str__(self):
        return self.nome

pessoa/forms.py
from django import forms
from django.contrib.auth.models import User
from .peopleUtils import adiciona_erro
class RegistraPessoaForm(forms.Form):

    nome        = forms.CharField(required=True)
    titulo      = forms.CharField(required=True)
    cpf         = forms.CharField(required=False)
    telefone    = forms.CharField(required=False)
    email       = forms.CharField(required=False)
    cep         = forms.CharField(required=False)
    rua         = forms.CharField(required=False)
    numero      = forms.CharField(required=False)
    bairro      = forms.CharField(required=False)
    apartamento = forms.CharField(required=False)
    bloco       = forms.CharField(required=False)
    complemento = forms.CharField(required=False)

    def is_valid(self):
        valid = True
        if not super(RegistraPessoaForm, self).is_valid():
            adiciona_erro('Por favor, verifique os dados informados!!')
            valid = False
        user_exists = User.objects.filter(nome=self.data['nome']).exists()

        if user_exists:
            adiciona_erro('Pessoa já cadastrada!')
            valid = False
        return valid

configuracao/views.py
from django.shortcuts import render

# Create your views here.

login/views.py
from login.usuarios import CadastrarUsuario
from login.login import Login

Login()
CadastrarUsuario()

pessoa/views.py
from django.shortcuts import render
from .people import PeopleDetails, PeopleSearch, CadastroPessoaView

def index(request):
    return render(request,'index.html')

CadastroPessoaView()

PeopleSearch()

PeopleDetails()



login/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width-device-width">
    <script src="{% static 'js/bootstrap.bundle.min.js'%}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-3.3.1.js'%}" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css'%}">
    <title>Login</title>
</head>
<body >
<div class="container">
    <div class="d-flex justify-content-center h-100">
        <div class="card">
            <div class="card-header">
                <h3>Login</h3>
            </div>
            <div class="card-body">
                <form action="{%url 'login'%}" method="post">
                    {%csrf_token%}
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" class="form-control" placeholder="Usuário" name="nome_user">
                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input type="password" class="form-control" placeholder="Senha" name="senha">
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Login" class="btn float-right login_btn">
                    </div>
                </form>
            </div>
             {%if form.errors %}
                    <div id="popup" class = "alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                             &times;
                        </button>
                        {{form.non_field_errors}}
                    </div>
            {% endif %}
        </div>
    </div>
</div>

</body>
</html>

login/templates/usuario.html
{% extends "pessoabase.html"%}
{%block body%}
<form id="form" action="{% url 'usuarios'%}" method="post">
    {%csrf_token%}
    <div id="box-user" class="form-signin-heading wrapper" >
          <div id="top-form">Novo Usuário</div><hr/>
          <div style="margin-bottom:05px"style="margin-bottom:05px"><input id="nome_user" class="form-control default-size" type="text" placeholder="Nome" name="nome_user"></div>
          <div style="margin-bottom:05px"><input id="usuario_user" class="form-control default-size" type="text" placeholder="Usuário" name="usuario"></div>
          <div style="margin-bottom:05px"><input id="senha_user" class="form-control default-size" type="password" placeholder="Senha" name="senha"></div>
          <div>
              <input id="perfil_user" class="form-check-input" type="checkbox" name="perfil">
              <label id="perfil_user_label" class="form-check-label">Administrador</label>
          </div>
          <hr/>
          <button id="salvar_user" style="margin-bottom:14px " class="btn btn-lg btn-primary btn-block default-size registrar" type="submit"> Registrar</button>
    </div>
    {%if form.errors %}
        <div id="popup" class = "alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                &times;
            </button>
            {{form.non_field_errors}}
        </div>
    {% endif %}
</form>
{%  endblock %}

pessoa/templates/details.html
{%extends "pessoabase.html"%}
{%block body%}
    <div id="label_details"><strong> DETALHES CADASTRAIS</strong></div>
    <div id="box_details">
        {%for pessoa in pessoas%}
            <div>Nome: </div>
            <div>{{pessoa|linebreaksbr}}</div>
            <div>Titulo: </div>
            <div>{{pessoa.titulo}}</div>
            <div>CPF:</div>
            <div>{{pessoa.cpf}}</div>
            <div>Telefone:</div>
            <div>{{pessoa.telefone}}</div>
            <div>E-mail:</div>
            <div>{{pessoa.email}}</div>
            <div>CEP:</div>
            <div>{{pessoa.cep}}</div>
            <div>Rua: </div>
            <div>{{pessoa.rua}}</div>
            <div>Numero: </div>
            <div>{{pessoa.numero}}</div>
            <div>Bairro: </div>
            <div>{{pessoa.bairro}}</div>
            <div>Apartamento:</div>
            <div>{{pessoa.apartamento}}</div>
            <div>Bloco:</div>
            <div> {{pessoa.bloco}}</div>
            <div>Complemento:</div>
            <div> {{pessoa.complemento}}</div>
    	{% endfor%}
    </div>
{%endblock%}

pessoa/templates/index.html
{%extends "pessoabase.html"%}
{%block body%}

{% endblock%}

pessoa/templates/pessoaForm.html
{% extends "pessoabase.html"%}
{% block body%}
<form id="form" class="form-signin-heading" action="{% url 'cadastro_pessoa'%}" method="post">
    {%csrf_token%}
    <h2 id="top-form" class="form-signin-heading">Criar Pessoa</h2>
    <hr/>
        <input style="margin-bottom:10px" id="id_nome" name="nome" type="text" class="form-control default-size" placeholder="Nome " required>
        <input style="margin-bottom:10px" id="id_titulo" name="titulo" type="text" class="form-control default-size" placeholder="Titulo " required>
        <input style="margin-bottom:10px"id="id_cpf" name="cpf" type="text" class="form-control default-size" placeholder="CPF">
        <input style="margin-bottom:10px" id="id_telefone" name="telefone" type="text" class=" form-control default-size" placeholder="Telefone">
        <input style="margin-bottom:10px" id="id_email" name="email" type="text" class=" form-control default-size" placeholder="E-mail">
        <input style="margin-bottom:10px" id="id_cep" name="cep" type="text" class="form-control default-size" placeholder="CEP">
        <input style="margin-bottom:10px" id="id_rua" name="rua" type="text" class="form-control default-size" placeholder="Rua" >
        <input style="margin-bottom:10px" id="id_numero" name="numero" type="text" class="form-control default-size" placeholder="Numero">
        <input style="margin-bottom:10px" id="id_bairro" name="bairro" type="text" class="form-control default-size" placeholder="Bairro">
        <input style="margin-bottom:10px" id="id_apartamento" name="apartamento" type="text" class="form-control default-size" placeholder="Apartamento">
        <input style="margin-bottom:10px" id="id_bloco" name="bloco" type="text" class="form-control default-size" placeholder="Bloco">
        <input style="margin-bottom:10px" id="id_complemento" name="complemento" type="text" class="form-control default-size" placeholder="Complemento">
<hr/>
    <button id="registrar" style="margin-bottom:14px " class="btn btn-lg btn-primary btn-block default-size registrar" type="submit">Registrar</button>
</form>
{% endblock %}

pessoa/templates/pessoa_search.html
{%extends "pessoabase.html"%}
{%block body%}
 <form class="form-signin-heading"  action="{%url 'pessoa_search'%}" method="post">
    {%csrf_token%}
     <div id="search">
        <input id="search-input" type="text" class="form-control default-size" placeholder="Informe um Nome ou Titulo" name="nome">
        <button id="search-button" class="btn btn-lg btn-primary btn-block default-size" type="submit" >BUSCAR</button>
    </div>
    <div class="wrapper grid-dados">
    	<div id="label-nome" >Nome </div>
    	<div id="label-titulo">Titulo </div>

    	{%for pessoa in pessoas%}
    		<div id="dados-nome" class="box">
    			<a href="{%url 'details' pessoa.id%}">{{pessoa|linebreaksbr}}</a>
    		</div>
        <div class="box">{{pessoa.titulo}}</div>
    	{% endfor%}
    </div>
 </form>
{% endblock%}

pessoa/templates/pessoabase.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="{% static 'js/jquery-3.3.1.js'%}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.min.js'%}" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/people.css'%}">

    <title>Pessoas</title>
</head>
<body>
<header id="topo">
    <img class="logo" src="{%static 'img/pessoa-icon.png'%}">
        <a href="/" title="Pessoas">PESSOAS</a>
        <a id="config" href="/usuario">Usuário</a>
</header>

<nav id="menu">
    <ul>
        <li><a href="/cadastro_pessoa"/>Cadastro de Pessoas</li>
        <li><a href="/pessoa_search"/>Pesquisar Pessoas</li>
        <li id="logout"><a href="#">Sair</a></li>
    </ul>
</nav>
<section id="conteudo">
            {%block body%}
            {%endblock%}
</section>
<footer id="rodape">
    <p></p>
</footer>

</body>
</html>

pessoa/templates/usuario.html
{% extends "pessoabase.htmml"%}
{%block body%}
<div>Novo Usuário</div>
<div><input type="text" placeholder="Nome"></div>
<div><input type="text" placeholder="Usuário"></div>
<div><input type="text" placeholder="Senha"></div>
<div><input type="submit" >REGISTRAR</div>

{%  endblock %}

templates/pessoabase.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="{% static 'js/jquery-3.3.1.js'%}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.min.js'%}" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/people.css'%}">

    <title>Pessoas</title>
</head>
<body>
<header id="topo">
    <img class="logo" src="{%static 'img/pessoa-icon.png'%}">
        <a href="/" title="Pessoas">PESSOAS</a>
</header>
<nav id="menu" >
    <ul>
        <li><a href="/cadastro_pessoa"/>Cadastro de Pessoas</li>
        <li><a href="/pessoa_search"/>Pesquisar Pessoas</li>
        <li><a id="config" href="/login/usuarios">Usuário</a></li>
        <li id="logout"><a href="/login">Sair</a></li>
    </ul>
</nav>
<section id="conteudo">
            {%block body%}
            {%endblock%}
</section>
<footer id="rodape">
    <p></p>
</footer>

</body>
</html>